[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[git_branch]
format = "on [$branch]($style) "
truncation_length = 32

[golang]
version_format = "${raw}"
format = "via [go@$version](bold cyan)"
