[general]
early-exit = true
initial-tool = "arrow"
output-filename = "~/Pictures/Screen Shot %Y %m %d at %H.%M.%S.png"
copy-command = "wl-copy"

[color-palette]
palette = [
    "#ff0000",
    "#ffd700",
    "#ff1493",
    "#2222ff",
]
